### WARNING -> AL MOMENTO SIA SUBSAMPLING CHE CLEANING NON FANNO BENE, (IL MOTIVO è CHE IL NOISE CHE C'è IN TRANING, C'è ANCHE IN TESTING E QUIDI UN 1000,1000,1000 IN TRANING STRAIGHT LO SARA ANCHE IN TEST)

In [1]:
import pandas as pd

df = pd.read_csv(r'C:\Users\franc\Desktop\TESI\SML_thesis_line_follower_robot\webots\data\data\sensors_data\training_data.csv')
df

,sensor0,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,target
0,10.880509,10.863198,10.845887,10.828577,10.811266,10.793955,10.776644,0
1,9.465424,9.451577,9.437731,9.423884,9.410037,9.396190,9.382343,0
2,38.519485,38.457984,38.396482,38.334981,7.888801,7.877731,7.866662,0
3,28.117520,28.070859,28.024198,27.977537,6.293761,6.284918,6.276074,0
4,18.699369,18.663467,18.627566,18.591665,4.649651,4.642590,4.635529,1
...,...,...,...,...,...,...,...,...
27290,4.186784,16.036718,15.988694,15.940669,15.892645,15.844621,4.129696,0
27291,3.999897,15.071325,15.033422,14.995520,14.957618,14.919716,3.954745,0
27292,3.792908,14.007751,13.977896,13.948041,13.918186,13.888331,3.757269,0
27293,3.568939,12.864290,12.840817,12.817344,12.793870,12.770397,3.540865,0
27294,3.331369,11.659470,11.641045,11.622620,11.604195,11.585771,3.309299,0

# remove noise

In [6]:
row_means = df[df.drop('target',axis=1).columns].mean(axis=1)
indices_with_zero_mean = df[df.drop('target',axis=1).columns].index[row_means == 1000]
indices_with_zero_mean_list = indices_with_zero_mean.tolist()

df = df.drop(indices_with_zero_mean_list)

print(f'Removed {len(indices_with_zero_mean_list)} rows')
df

Removed 0 rows

,sensor0,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,target
0,10.880509,10.863198,10.845887,10.828577,10.811266,10.793955,10.776644,0
1,9.465424,9.451577,9.437731,9.423884,9.410037,9.396190,9.382343,0
2,38.519485,38.457984,38.396482,38.334981,7.888801,7.877731,7.866662,0
3,28.117520,28.070859,28.024198,27.977537,6.293761,6.284918,6.276074,0
4,18.699369,18.663467,18.627566,18.591665,4.649651,4.642590,4.635529,1
...,...,...,...,...,...,...,...,...
27290,4.186784,16.036718,15.988694,15.940669,15.892645,15.844621,4.129696,0
27291,3.999897,15.071325,15.033422,14.995520,14.957618,14.919716,3.954745,0
27292,3.792908,14.007751,13.977896,13.948041,13.918186,13.888331,3.757269,0
27293,3.568939,12.864290,12.840817,12.817344,12.793870,12.770397,3.540865,0
27294,3.331369,11.659470,11.641045,11.622620,11.604195,11.585771,3.309299,0

In [7]:
df.to_csv(r'C:\Users\franc\Desktop\TESI\SML_thesis_line_follower_robot\webots\data\data\sensors_data\cleaned.csv',index=False)

## Sampling

In [2]:
from imblearn.under_sampling import RandomUnderSampler

X, y = df.drop('target',axis=1),df['target']
undersample = RandomUnderSampler(sampling_strategy='majority')
X_over, y_over = undersample.fit_resample(X, y)

In [3]:
df_sampled = pd.DataFrame(X_over)
df_sampled['target'] = y_over
df_sampled = df_sampled.sort_index()
df_sampled

,sensor0,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,target
2,38.519485,38.457984,38.396482,38.334981,7.888801,7.877731,7.866662,0
4,18.699369,18.663467,18.627566,18.591665,4.649651,4.642590,4.635529,1
8,13.791358,13.570005,13.348653,13.127300,3.571401,3.527299,3.483196,1
9,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,0
12,7.863592,7.514367,7.165143,6.815918,2.292510,2.222710,2.152910,1
...,...,...,...,...,...,...,...,...
27266,2.980967,9.694247,9.481353,9.268458,9.055564,8.842670,2.725553,0
27269,9.991554,9.868404,9.745255,9.622105,9.498955,9.375806,2.849964,1
27275,3.472075,12.256022,12.123787,11.991551,11.859316,11.727081,3.313750,0
27280,12.979036,12.935732,12.892428,12.849125,12.805821,12.762517,3.535121,1
27291,3.999897,15.071325,15.033422,14.995520,14.957618,14.919716,3.954745,0

In [7]:
df_sampled.to_csv(r'C:\Users\franc\Desktop\TESI\SML_thesis_line_follower_robot\webots\data\data\sensors_data\sampled.csv',index=False)

In [4]:
df_sampled['target'].value_counts()

target
1    2419
0    2322
2    2322
Name: count, dtype: int64

In [5]:
df['target'].value_counts()

target
0    22554
1     2419
2     2322
Name: count, dtype: int64